#include "zig.h"
zig_extern zig_void start(zig_void);
zig_extern zig_O__Users_momo_projects_lua_2dmultiplatform_zig_2dcache_o_d532e661f7d6dc5d555e9c07505756a6_cimport_struct_lua_State * luaL_newstate(zig_void);
zig_extern zig_void luaL_openlibs(zig_O__Users_momo_projects_lua_2dmultiplatform_zig_2dcache_o_d532e661f7d6dc5d555e9c07505756a6_cimport_struct_lua_State * const a0);
zig_extern zig_isize write(zig_c_int const a0, zig_u8 const * const a1, zig_usize const a2);
zig_extern zig_c_int * __error(zig_void);
zig_extern zig_noreturn abort(zig_void);
zig_extern zig_u32 _dyld_image_count(zig_void);
zig_extern zig_usize _dyld_get_image_vmaddr_slide(zig_u32 const a0);
zig_extern zig_S_macho_mach_header__7021 * _dyld_get_image_header(zig_u32 const a0);
zig_extern zig_u8 const * _dyld_get_image_name(zig_u32 const a0);
zig_extern zig_void os_unfair_lock_lock(zig_S_c_darwin_os_unfair_lock__6300 * const a0);
zig_extern zig_c_int pthread_threadid_np(zig_O_c_pthread_t__opaque_9041 * const a0, zig_u64 * const a1);
zig_extern zig_void * mmap(zig_void * const a0, zig_usize const a1, zig_c_uint const a2, zig_c_uint const a3, zig_c_int const a4, zig_i64 const a5);
zig_extern zig_void os_unfair_lock_unlock(zig_S_c_darwin_os_unfair_lock__6300 * const a0);
zig_extern zig_c_int __ulock_wait2(zig_u32 const a0, zig_void const * const a1, zig_u64 const a2, zig_u64 const a3, zig_u64 const a4);
zig_extern zig_c_int close$NOCANCEL(zig_c_int const a0);
zig_extern zig_isize read(zig_c_int const a0, zig_u8 * const a1, zig_usize const a2);
zig_extern zig_c_int munmap(zig_void const * const a0, zig_usize const a1);
zig_extern zig_u8 * getenv(zig_u8 const * const a0);
zig_extern zig_c_int openat(zig_c_int const a0, zig_u8 const * const a1, zig_c_uint const a2, ...);
zig_extern zig_c_int fcntl(zig_c_int const a0, zig_c_int const a1, ...);
zig_extern zig_c_int fstat(zig_c_int const a0, zig_S_c_darwin_Stat__9923 * const a1);
zig_extern zig_c_int isatty(zig_c_int const a0);
zig_extern zig_c_int msync(zig_void const * const a0, zig_usize const a1, zig_c_int const a2);
